beds/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('patient_reg/', views.patient_reg, name='patient_reg'),
]

covidportal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path('beds/', include('beds.urls')),
    path('admin/', admin.site.urls),
]

beds/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
dt = (
    ('AL','Alapuzha'),
    ('ER','Ernakulam'),
    ('ID','Iduki'),
    ('KN','Kannur'),
    ('KL','Kollam'),
    ('KS','Kasargod'),
    ('KT','Kottayam'),
    ('KZ','Kozhikode'),
    ('MA','Malapuram'),
    ('PL','Palakkad'),
    ('PT','Pathanamthitta'),
    ('TV','Thiruvanathapuram'),
    ('TS','Thrissur'),
    ('WA','Wayanad')
)

class Hospital(models.Model):
    sc = (
        ('gov','government'),
        ('prv','private')
    )

    name = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    district = models.CharField(max_length=2,choices=dt)
    phone = models.CharField(max_length=15)
    sector = models.CharField(max_length=3,choices=sc)
    covid_beds = models.IntegerField()
    normal_beds = models.IntegerField()
    icu_beds = models.IntegerField()
    ventilator = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE,blank=True,null=True)


    def __str__(self):
        return self.name+" "+self.location

class Patient(models.Model):
    ct =(
        ('cv','Covid'),
        ('NC','Non-covid')
    )
    st = (
        ('W','Waiting'),
        ('A','Admitted'),
        ('D', 'Discharged')
    )        
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    adharno = models.IntegerField()
    phone = models.CharField(max_length=15)
    location = models.CharField(max_length=50)
    district = models.CharField(max_length=2,choices=dt)
    category = models.CharField(max_length=2,choices=ct)
    # status = models.CharField(max_length=2,choices=st)
    status = models.CharField(max_length=2,choices=st,blank=True,default='W') #to make this field not required and default value W

    def __str__(self):
        return self.name


class BedAllocation(models.Model):
    ct = (
        ('C','Covid'),
        ('N','Normal'),
        ('I','Icu'),
        ('V','Ventilator')
    )        
    patient = models.ForeignKey(Patient,on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospital,on_delete=models.CASCADE)
    category =models.CharField(max_length=2,choices=ct)

    def __str__(self):  
        return str(self.patient) #return self.patient will return a non-string so add str(self.patient) to make it string

beds/forms.py
from django.forms import ModelForm
from .models import Patient

class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = ['name', 'age','location', 'district', 'phone', 'adharno', 'category']

beds/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Hospital, Patient, BedAllocation
from django.db.models import Sum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import PatientForm
from django.shortcuts import redirect

# Create your views here.
# from django.http import HttpResponse


# def index(request):
#     return HttpResponse("Hello world. You're at the polls index.")

# def index(request):
#     return render(request, 'beds/summary.html')
# @login_required
# def dashboard(request):
#     return render(request, 'beds/dashboard.html')

def index(request):
    normal_beds = Hospital.objects.aggregate(total=Sum('normal_beds'))
    covid_beds = Hospital.objects.aggregate(total=Sum('covid_beds'))
    icu = Hospital.objects.aggregate(total=Sum('icu_beds'))
    ventilator = Hospital.objects.aggregate(total=Sum('ventilator'))

    page = request.GET.get('page', 1)
    hospital_list = Hospital.objects.all()
    paginator = Paginator(hospital_list, 5)
    try:
        hospitals = paginator.page(page)
    except PageNotAnInteger:
        hospitals = paginator.page(1)
    except EmptyPage:
        hospitals = paginator.page(paginator.num_pages)

    context = {
        'normal_beds': normal_beds,
        'covid_beds': covid_beds,
        'icu': icu,
        'ventilator': ventilator,
        'hospitals': hospitals
    }
    return render(request, 'beds/summary.html', context)

@login_required
def dashboard(request):
    
    return render(request, 'beds/dashboard.html')

def patient_reg(request):
    form = PatientForm(request.POST or None)
    context= {
    'form':form
    }
    if form.is_valid():
        form.save()
        return redirect('index')
    return render(request, 'beds/patient_registration.html', context)

beds/templates/beds/bedallocate.html
{% extends 'beds/index.html' %}

{% block content %}
<div class="container m-4 p-4">

  <div class="container mx-auto border p-4" style="width:50%;">
    <h3 class="text-danger"> Bed Allocation </h3> <hr>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <hr>
      <input type="submit" class="btn btn-danger" value="Allocate">
    </form>
  </div>
</div>
{% endblock %}

beds/templates/beds/dashboard.html
{% extends 'beds/index.html' %}

{% block content %}
<h2> Welcome {{  user.username }}</h2>
{% endblock %}

beds/templates/beds/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'beds/css/styles.css' %}">
    <title>Covid Portal</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg bg-navy navbar-dark">
        <a class="navbar-brand ml-5" href="#"><i class="fa fa-heartbeat fa-lg"></i> Covid Portal</a>

        {% if user.is_authenticated %}
           
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}"><i class="fa fa-home"></i> Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard </a>
          </li>
          <!-- Dropdown -->
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
             <i class="fa fa-user-circle"></i> {{ user.username }}
           </a>
           <div class="dropdown-menu">
             <a class="dropdown-item" href="{% url 'logout' %}">Logut</a>
           </div>
         </li>
        </ul>

        {% else %}

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto mr-5">
            <a class="nav-link mr-4 hospital_login_nav" href="{% url 'login' %}"><i class="fa fa-lock"></i> Hospital Login</a>
            <button type="button" class="btn ml-5 nav-patient"><i class="fa fa-user-o"></i><a href="{% url 'patient_reg' %}">Patient registration</a></button>
          </div>
        </div>

        {% endif %}

      </nav>

      <div class="container">
      {% block content %} 
      
      {% endblock %}
      </div>

      <footer class="footer" style=" width:100%;">
        <div class="container-fluid p-4" >
          <p class="text-center"> &copy; 2021. All Rights Reserved.</p>
        </div>
      </footer>

      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>      

</body>
</html>

beds/templates/beds/patient_registration.html
{% extends 'beds/index.html' %}

{% block content %}
<div class="container m-4 p-4">
  <h3> Patient Registration </h3>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-danger">
  </form>
</div>
{% endblock %}

beds/templates/beds/summary.html
{% extends 'beds/index.html' %}

{% block content %} 

<div class="card_group">
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 justify-content-center">
  
  <div class="col mb-4">
    <div class="card bg-success">
      
      <div class="card-body text-center">
        <h5 class="card-title"><b>NORMAL BEDS</b></h5>
        <p class="card-text">{{ normal_beds.total }}</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card bg-warning">
      
      <div class="card-body text-center">
        <h5 class="card-title"><b>COVID BEDS</b></h5>
        <p class="card-text">{{ covid_beds.total }}</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card bg-primary">
      
      <div class="card-body text-center">
        <h5 class="card-title"><b>ICU BEDS</b></h5>
        <p class="card-text">{{ icu.total }}</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card bg-danger  ">
      
      <div class="card-body text-center">
        <h5 class="card-title"><b>VENTILATOR</b></h5>
        <p class="card-text">{{ ventilator.total }}</p>
      </div>
    </div>
  </div>

</div> 
</div> 


<div class="container mt-5">
  <h3 class="mb-3">Hospital Information</h3>
  <input class="form-control" id="myInput" type="text" placeholder="Search..">
  <br>
  <table class="table table-bordered table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th>NAME</th>
        <th>LOCATION</th>
        <th>DISTRICT</th>
        <th>NORMAL BEDS</th>
        <th>COVID BEDS</th>
        <th>ICU</th>
        <th>VENTILATOR</th>
      </tr>
    </thead>
    <tbody id="myTable">
     {% for hospital in hospitals %} 
      <tr>
        <td>{{ hospital.name }}</td>
        <td>{{ hospital.location}}</td>
        <td>{{ hospital.get_district_display}}</td>
        <td>{{ hospital.normal_beds}}</td>
        <td>{{ hospital.covid_beds}}</td>
        <td>{{ hospital.icu_beds}}</td>
        <td>{{ hospital.ventilator}}</td>
      </tr>
     {% endfor %} 
    </tbody>
  </table>

  {% if hospitals.has_other_pages %}
  <nav aria-label="Pagination">
    <ul class="pagination justify-content-center">
      {% if hospitals.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ hospitals.previous_page_number }}">Previous</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Previous</a></li>
      {% endif %}
      {% for i in hospitals.paginator.page_range %}
        {% if hospitals.number == i %}
          <li class="page-item active"><a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if hospitals.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ hospitals.next_page_number }}">Next</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
  <div style="height:120px;"></div>

</div>


<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
  

{% endblock %}